version: '3.4'

services:
  client:
    image: client-diets-app
    build:
      context: my-app
      dockerfile: ./Dockerfile
    depends_on:  
      - server
    ports:
      - 3000:3000
    network_mode: "host"
  server:
    image: server-diets-app
    build:
      context: node-postgres
      dockerfile: ./Dockerfile
    depends_on:  
      - postgres
    ports:
      - 3001:3001
    network_mode: "host"
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=diets-app
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
  
